name: union_type_annotation
description: Union type annotation
version: 1.0.0
homepage: https://github.com/andry-brill/a-union-type
repository: https://github.com/andry-brill/a-union-type
issue_tracker: https://github.com/andry-brill/a-union-type/issues
environment:
  sdk: ^3.10.1
